<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>formulario 1</title>
</head>
<body>
<form action="respuesta.php" method="get">


<label for="nombre"></label>
nombre  
<input type="text" name="nombre">
<br>

<label for="apellido"></label>
apellido 
<input type="text" name="apellido">
<br>

<label for="numero"></label>
numero favorito 
<input type="number" name="numero">
<br>

<input type="submit" value="Enviar este formulario" />

</form>
</body>
</html>

